use_frameworks!

target 'MideaSmartCommon_Example' do
#  pod 'MideaSmartCommon', :path => '../'
pod "MideaSmartCommon"

  target 'MideaSmartCommon_Tests' do
    inherit! :search_paths

    
  end
end
